### ISSUE TITLE
help find your package

### ISSUE THREAD

**Issue by Scrum** [posthtml/posthtml-rename-attrs#1]
@madzhup Hi, I am a posthtml package maintainer, I found your package because you have a posthtml package in dependencies. I think it will be easier for people to find your package if you add it to the list of plugins [here](https://github.com/posthtml/posthtml#plugins) and [here](https://github.com/posthtml/posthtml-plugins/), and of course the first thing to do in the posthtml organization itself - I can move your package to the posthtml organization for more popularity, for this it will be necessary to add me to this repository and then I will transfer it. The package itself will remain under your control.

let me know about any decision you make, i will understand if you are not interested

**Comment by Scrum** [comment]
@madzhup I will need more rights to do this, at the moment I have no option `settings`

**Comment by madzhup** [comment]
There are no option for more rights. Only ownership transfer.

**Comment by Scrum** [comment]
> Transfer ownership

> Transfer this repository to another user or to an organization where you have the ability to create repositories. 

not having the right owner, I can not move it to the organization

**Comment by Scrum** [comment]
@madzhup Please let me know if this does not suit you, I will close the task. You can also place links to your packages as described above.

**Comment by madzhup** [comment]
Everything is ok, transfered to you.

**Comment by Scrum** [comment]
Good day for this package)

**Comment by Scrum** [comment]
@madzhup You can do the same for other posthtml plugins.

And be sure to know if everything is fine with your access.

**Comment by madzhup** [comment]
I transferred to you all of my posthtml plugins, I don't use its for long time and don't plan to support. Maybe someone be interested.

**Comment by Scrum** [comment]
Unfortunately it was not possible to translate `posthtml-jsx-svg`, made a return request `posthtml already has a repository in the posthtml/posthtml-jsx network`

**Comment by Scrum** [comment]
> I transferred to you all of my posthtml plugins, I don't use its for long time and don't plan to support. Maybe someone be interested.

Thank you, it would be great to get access to them in npm if possible.

**Comment by madzhup** [comment]
Just send me account at npm

**Comment by Scrum** [comment]
@madzhup  [scrum](https://www.npmjs.com/~scrum)

**Comment by madzhup** [comment]
Done

**Comment by Scrum** [comment]
Muchas gracias amigo
